/home/kevin/bin/seqtk seq p1/sample_D9-1-clipped_filtered.fq -b ATATGT -B IIIIII > o/sample_D9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F9-2-clipped_filtered.fq -b CATAAGT -B IIIIIII > o/sample_F9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D5-singles-clipped_filtered.fq -b GAGATA -B IIIIII > o/sample_D5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A3-singles-clipped_filtered.fq -b ACTA -B IIII > o/sample_A3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D5-2-clipped_filtered.fq -b GAGATA -B IIIIII > o/sample_D5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D8-2-clipped_filtered.fq -b ACCTAA -B IIIIII > o/sample_D8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H6-1-clipped_filtered.fq -b CGCGGAGA -B IIIIIIII > o/sample_H6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C3-2-clipped_filtered.fq -b CCTAG -B IIIII > o/sample_C3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B4-singles-clipped_filtered.fq -b ACAAA -B IIIII > o/sample_B4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F6-singles-clipped_filtered.fq -b ACGTGTT -B IIIIIII > o/sample_F6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H6-2-clipped_filtered.fq -b CGCGGAGA -B IIIIIIII > o/sample_H6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A5-2-clipped_filtered.fq -b AACT -B IIII > o/sample_A5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E10-singles-clipped_filtered.fq -b ATGAAAG -B IIIIIII > o/sample_E10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C7-singles-clipped_filtered.fq -b TAATA -B IIIII > o/sample_C7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F12-2-clipped_filtered.fq -b CTACGGA -B IIIIIII > o/sample_F12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F4-1-clipped_filtered.fq -b AACGCCT -B IIIIIII > o/sample_F4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F10-singles-clipped_filtered.fq -b CGCTGAT -B IIIIIII > o/sample_F10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D12-1-clipped_filtered.fq -b CGCGGT -B IIIIII > o/sample_D12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H5-1-clipped_filtered.fq -b CCATGGGT -B IIIIIIII > o/sample_H5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A9-1-clipped_filtered.fq -b AGGG -B IIII > o/sample_A9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F12-1-clipped_filtered.fq -b CTACGGA -B IIIIIII > o/sample_F12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G10-1-clipped_filtered.fq -b TGGTACGT -B IIIIIIII > o/sample_G10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B5-2-clipped_filtered.fq -b TTCTG -B IIIII > o/sample_B5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D4-2-clipped_filtered.fq -b CTTCCA -B IIIIII > o/sample_D4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D12-2-clipped_filtered.fq -b CGCGGT -B IIIIII > o/sample_D12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A5-singles-clipped_filtered.fq -b AACT -B IIII > o/sample_A5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F8-2-clipped_filtered.fq -b ATTGGAT -B IIIIIII > o/sample_F8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C4-singles-clipped_filtered.fq -b GAGGA -B IIIII > o/sample_C4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G6-1-clipped_filtered.fq -b ACGACTAG -B IIIIIIII > o/sample_G6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H3-1-clipped_filtered.fq -b ACAGGGAA -B IIIIIIII > o/sample_H3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H7-1-clipped_filtered.fq -b CGTGTGGT -B IIIIIIII > o/sample_H7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G8-singles-clipped_filtered.fq -b TAGGCCAT -B IIIIIIII > o/sample_G8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E12-2-clipped_filtered.fq -b GAATTCA -B IIIIIII > o/sample_E12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D10-1-clipped_filtered.fq -b ATCGTA -B IIIIII > o/sample_D10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C4-1-clipped_filtered.fq -b GAGGA -B IIIII > o/sample_C4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G7-2-clipped_filtered.fq -b TAGCATGG -B IIIIIIII > o/sample_G7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E7-1-clipped_filtered.fq -b TGGCTA -B IIIIII > o/sample_E7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C10-2-clipped_filtered.fq -b GGTTGT -B IIIIII > o/sample_C10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G5-singles-clipped_filtered.fq -b TGCTGGA -B IIIIIII > o/sample_G5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B12-2-clipped_filtered.fq -b AGGAT -B IIIII > o/sample_B12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F7-1-clipped_filtered.fq -b ATTAATT -B IIIIIII > o/sample_F7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D11-2-clipped_filtered.fq -b CATCGT -B IIIIII > o/sample_D11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E11-singles-clipped_filtered.fq -b AAAAGTT -B IIIIIII > o/sample_E11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G10-singles-clipped_filtered.fq -b TGGTACGT -B IIIIIIII > o/sample_G10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G4-1-clipped_filtered.fq -b TCTGTGA -B IIIIIII > o/sample_G4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F5-1-clipped_filtered.fq -b AATATGG -B IIIIIII > o/sample_F5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H6-singles-clipped_filtered.fq -b CGCGGAGA -B IIIIIIII > o/sample_H6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G12-2-clipped_filtered.fq -b CCGGATAT -B IIIIIIII > o/sample_G12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E3-2-clipped_filtered.fq -b GGAAGA -B IIIIII > o/sample_E3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A12-2-clipped_filtered.fq -b TGCGA -B IIIII > o/sample_A12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A4-2-clipped_filtered.fq -b CAGA -B IIII > o/sample_A4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A12-1-clipped_filtered.fq -b TGCGA -B IIIII > o/sample_A12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C12-2-clipped_filtered.fq -b TTCAGA -B IIIIII > o/sample_C12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H4-1-clipped_filtered.fq -b ACGTGGTA -B IIIIIIII > o/sample_H4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F4-singles-clipped_filtered.fq -b AACGCCT -B IIIIIII > o/sample_F4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A9-2-clipped_filtered.fq -b AGGG -B IIII > o/sample_A9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F6-1-clipped_filtered.fq -b ACGTGTT -B IIIIIII > o/sample_F6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E11-2-clipped_filtered.fq -b AAAAGTT -B IIIIIII > o/sample_E11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A1-2-clipped_filtered.fq -b CTCG -B IIII > o/sample_A1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E7-singles-clipped_filtered.fq -b TGGCTA -B IIIIII > o/sample_E7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E9-singles-clipped_filtered.fq -b CTTGCTT -B IIIIIII > o/sample_E9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G5-1-clipped_filtered.fq -b TGCTGGA -B IIIIIII > o/sample_G5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F9-singles-clipped_filtered.fq -b CATAAGT -B IIIIIII > o/sample_F9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G3-singles-clipped_filtered.fq -b TCGAAGA -B IIIIIII > o/sample_G3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D4-1-clipped_filtered.fq -b CTTCCA -B IIIIII > o/sample_D4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A6-1-clipped_filtered.fq -b GCGT -B IIII > o/sample_A6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G1-2-clipped_filtered.fq -b GCGGAAT -B IIIIIII > o/sample_G1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C1-1-clipped_filtered.fq -b ATTGA -B IIIII > o/sample_C1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H8-2-clipped_filtered.fq -b GCTGTGGA -B IIIIIIII > o/sample_H8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E8-singles-clipped_filtered.fq -b TATTTTT -B IIIIIII > o/sample_E8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E5-2-clipped_filtered.fq -b GTTGAA -B IIIIII > o/sample_E5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E12-singles-clipped_filtered.fq -b GAATTCA -B IIIIIII > o/sample_E12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E5-singles-clipped_filtered.fq -b GTTGAA -B IIIIII > o/sample_E5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B12-1-clipped_filtered.fq -b AGGAT -B IIIII > o/sample_B12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A8-1-clipped_filtered.fq -b GTAA -B IIII > o/sample_A8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E3-1-clipped_filtered.fq -b GGAAGA -B IIIIII > o/sample_E3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G4-singles-clipped_filtered.fq -b TCTGTGA -B IIIIIII > o/sample_G4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C7-2-clipped_filtered.fq -b TAATA -B IIIII > o/sample_C7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B10-1-clipped_filtered.fq -b GCTTA -B IIIII > o/sample_B10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F12-singles-clipped_filtered.fq -b CTACGGA -B IIIIIII > o/sample_F12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H11-2-clipped_filtered.fq -b TATCGGGA -B IIIIIIII > o/sample_H11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A12-singles-clipped_filtered.fq -b TGCGA -B IIIII > o/sample_A12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G2-1-clipped_filtered.fq -b TAGCGGA -B IIIIIII > o/sample_G2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G12-1-clipped_filtered.fq -b CCGGATAT -B IIIIIIII > o/sample_G12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F8-1-clipped_filtered.fq -b ATTGGAT -B IIIIIII > o/sample_F8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A10-1-clipped_filtered.fq -b GATG -B IIII > o/sample_A10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B8-1-clipped_filtered.fq -b CTGTA -B IIIII > o/sample_B8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H3-2-clipped_filtered.fq -b ACAGGGAA -B IIIIIIII > o/sample_H3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A6-2-clipped_filtered.fq -b GCGT -B IIII > o/sample_A6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C2-2-clipped_filtered.fq -b CATCT -B IIIII > o/sample_C2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H11-1-clipped_filtered.fq -b TATCGGGA -B IIIIIIII > o/sample_H11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B7-singles-clipped_filtered.fq -b GTATT -B IIIII > o/sample_B7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F11-2-clipped_filtered.fq -b CGGTAGA -B IIIIIII > o/sample_F11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D1-2-clipped_filtered.fq -b TAGGAA -B IIIIII > o/sample_D1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H9-1-clipped_filtered.fq -b GGATTGGT -B IIIIIIII > o/sample_H9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C1-singles-clipped_filtered.fq -b ATTGA -B IIIII > o/sample_C1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C11-1-clipped_filtered.fq -b CCAGCT -B IIIIII > o/sample_C11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E1-1-clipped_filtered.fq -b CTATTA -B IIIIII > o/sample_E1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F7-singles-clipped_filtered.fq -b ATTAATT -B IIIIIII > o/sample_F7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C11-singles-clipped_filtered.fq -b CCAGCT -B IIIIII > o/sample_C11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F1-2-clipped_filtered.fq -b GAACTTG -B IIIIIII > o/sample_F1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D7-2-clipped_filtered.fq -b AGTGGA -B IIIIII > o/sample_D7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D4-singles-clipped_filtered.fq -b CTTCCA -B IIIIII > o/sample_D4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H1-2-clipped_filtered.fq -b CGCCTTAT -B IIIIIIII > o/sample_H1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B3-singles-clipped_filtered.fq -b CTAGG -B IIIII > o/sample_B3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E4-2-clipped_filtered.fq -b GTACTT -B IIIIII > o/sample_E4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E1-singles-clipped_filtered.fq -b CTATTA -B IIIIII > o/sample_E1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E3-singles-clipped_filtered.fq -b GGAAGA -B IIIIII > o/sample_E3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D2-2-clipped_filtered.fq -b GCTCTA -B IIIIII > o/sample_D2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C10-singles-clipped_filtered.fq -b GGTTGT -B IIIIII > o/sample_C10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H4-2-clipped_filtered.fq -b ACGTGGTA -B IIIIIIII > o/sample_H4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C12-singles-clipped_filtered.fq -b TTCAGA -B IIIIII > o/sample_C12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H8-1-clipped_filtered.fq -b GCTGTGGA -B IIIIIIII > o/sample_H8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G11-2-clipped_filtered.fq -b TCTCAGTG -B IIIIIIII > o/sample_G11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D1-1-clipped_filtered.fq -b TAGGAA -B IIIIII > o/sample_D1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E6-2-clipped_filtered.fq -b TAACGA -B IIIIII > o/sample_E6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B2-singles-clipped_filtered.fq -b TCACG -B IIIII > o/sample_B2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G9-2-clipped_filtered.fq -b TGCAAGGA -B IIIIIIII > o/sample_G9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E2-2-clipped_filtered.fq -b GCCAGT -B IIIIII > o/sample_E2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G8-1-clipped_filtered.fq -b TAGGCCAT -B IIIIIIII > o/sample_G8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G4-2-clipped_filtered.fq -b TCTGTGA -B IIIIIII > o/sample_G4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H2-1-clipped_filtered.fq -b AACCGAGA -B IIIIIIII > o/sample_H2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F1-singles-clipped_filtered.fq -b GAACTTG -B IIIIIII > o/sample_F1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B1-singles-clipped_filtered.fq -b CGCTT -B IIIII > o/sample_B1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H7-singles-clipped_filtered.fq -b CGTGTGGT -B IIIIIIII > o/sample_H7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A4-1-clipped_filtered.fq -b CAGA -B IIII > o/sample_A4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H4-singles-clipped_filtered.fq -b ACGTGGTA -B IIIIIIII > o/sample_H4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B10-singles-clipped_filtered.fq -b GCTTA -B IIIII > o/sample_B10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A5-1-clipped_filtered.fq -b AACT -B IIII > o/sample_A5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G5-2-clipped_filtered.fq -b TGCTGGA -B IIIIIII > o/sample_G5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B5-1-clipped_filtered.fq -b TTCTG -B IIIII > o/sample_B5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A11-2-clipped_filtered.fq -b TCAG -B IIII > o/sample_A11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E4-singles-clipped_filtered.fq -b GTACTT -B IIIIII > o/sample_E4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C5-1-clipped_filtered.fq -b GGAAG -B IIIII > o/sample_C5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G2-2-clipped_filtered.fq -b TAGCGGA -B IIIIIII > o/sample_G2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H10-singles-clipped_filtered.fq -b GTGAGGGT -B IIIIIIII > o/sample_H10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G11-1-clipped_filtered.fq -b TCTCAGTG -B IIIIIIII > o/sample_G11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E8-1-clipped_filtered.fq -b TATTTTT -B IIIIIII > o/sample_E8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A11-1-clipped_filtered.fq -b TCAG -B IIII > o/sample_A11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B3-2-clipped_filtered.fq -b CTAGG -B IIIII > o/sample_B3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H5-2-clipped_filtered.fq -b CCATGGGT -B IIIIIIII > o/sample_H5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F7-2-clipped_filtered.fq -b ATTAATT -B IIIIIII > o/sample_F7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A3-1-clipped_filtered.fq -b ACTA -B IIII > o/sample_A3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B9-1-clipped_filtered.fq -b ACCGT -B IIIII > o/sample_B9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G3-1-clipped_filtered.fq -b TCGAAGA -B IIIIIII > o/sample_G3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D7-singles-clipped_filtered.fq -b AGTGGA -B IIIIII > o/sample_D7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B12-singles-clipped_filtered.fq -b AGGAT -B IIIII > o/sample_B12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D6-1-clipped_filtered.fq -b ATGCCT -B IIIIII > o/sample_D6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H10-1-clipped_filtered.fq -b GTGAGGGT -B IIIIIIII > o/sample_H10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F2-singles-clipped_filtered.fq -b GGACCTA -B IIIIIII > o/sample_F2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E10-2-clipped_filtered.fq -b ATGAAAG -B IIIIIII > o/sample_E10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D12-singles-clipped_filtered.fq -b CGCGGT -B IIIIII > o/sample_D12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F11-1-clipped_filtered.fq -b CGGTAGA -B IIIIIII > o/sample_F11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B11-2-clipped_filtered.fq -b GGTGT -B IIIII > o/sample_B11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E4-1-clipped_filtered.fq -b GTACTT -B IIIIII > o/sample_E4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F11-singles-clipped_filtered.fq -b CGGTAGA -B IIIIIII > o/sample_F11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D11-1-clipped_filtered.fq -b CATCGT -B IIIIII > o/sample_D11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F1-1-clipped_filtered.fq -b GAACTTG -B IIIIIII > o/sample_F1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A2-1-clipped_filtered.fq -b TGCA -B IIII > o/sample_A2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F2-2-clipped_filtered.fq -b GGACCTA -B IIIIIII > o/sample_F2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G9-singles-clipped_filtered.fq -b TGCAAGGA -B IIIIIIII > o/sample_G9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H1-singles-clipped_filtered.fq -b CGCCTTAT -B IIIIIIII > o/sample_H1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F3-singles-clipped_filtered.fq -b GTCGATT -B IIIIIII > o/sample_F3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D3-singles-clipped_filtered.fq -b CCACAA -B IIIIII > o/sample_D3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D8-singles-clipped_filtered.fq -b ACCTAA -B IIIIII > o/sample_D8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E7-2-clipped_filtered.fq -b TGGCTA -B IIIIII > o/sample_E7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D6-2-clipped_filtered.fq -b ATGCCT -B IIIIII > o/sample_D6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H5-singles-clipped_filtered.fq -b CCATGGGT -B IIIIIIII > o/sample_H5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A2-singles-clipped_filtered.fq -b TGCA -B IIII > o/sample_A2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D2-singles-clipped_filtered.fq -b GCTCTA -B IIIIII > o/sample_D2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E11-1-clipped_filtered.fq -b AAAAGTT -B IIIIIII > o/sample_E11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B2-1-clipped_filtered.fq -b TCACG -B IIIII > o/sample_B2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H12-2-clipped_filtered.fq -b TTCCTGGA -B IIIIIIII > o/sample_H12-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C8-2-clipped_filtered.fq -b TACAT -B IIIII > o/sample_C8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A8-2-clipped_filtered.fq -b GTAA -B IIII > o/sample_A8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B6-2-clipped_filtered.fq -b AGCCG -B IIIII > o/sample_B6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C12-1-clipped_filtered.fq -b TTCAGA -B IIIIII > o/sample_C12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B6-1-clipped_filtered.fq -b AGCCG -B IIIII > o/sample_B6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A1-1-clipped_filtered.fq -b CTCG -B IIII > o/sample_A1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E10-1-clipped_filtered.fq -b ATGAAAG -B IIIIIII > o/sample_E10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E2-singles-clipped_filtered.fq -b GCCAGT -B IIIIII > o/sample_E2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C3-singles-clipped_filtered.fq -b CCTAG -B IIIII > o/sample_C3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B11-singles-clipped_filtered.fq -b GGTGT -B IIIII > o/sample_B11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B9-singles-clipped_filtered.fq -b ACCGT -B IIIII > o/sample_B9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A10-2-clipped_filtered.fq -b GATG -B IIII > o/sample_A10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E2-1-clipped_filtered.fq -b GCCAGT -B IIIIII > o/sample_E2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H1-1-clipped_filtered.fq -b CGCCTTAT -B IIIIIIII > o/sample_H1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B4-1-clipped_filtered.fq -b ACAAA -B IIIII > o/sample_B4-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A7-1-clipped_filtered.fq -b CGAT -B IIII > o/sample_A7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G7-singles-clipped_filtered.fq -b TAGCATGG -B IIIIIIII > o/sample_G7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F3-2-clipped_filtered.fq -b GTCGATT -B IIIIIII > o/sample_F3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G6-singles-clipped_filtered.fq -b ACGACTAG -B IIIIIIII > o/sample_G6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F5-singles-clipped_filtered.fq -b AATATGG -B IIIIIII > o/sample_F5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C8-singles-clipped_filtered.fq -b TACAT -B IIIII > o/sample_C8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B10-2-clipped_filtered.fq -b GCTTA -B IIIII > o/sample_B10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G12-singles-clipped_filtered.fq -b CCGGATAT -B IIIIIIII > o/sample_G12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F2-1-clipped_filtered.fq -b GGACCTA -B IIIIIII > o/sample_F2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B4-2-clipped_filtered.fq -b ACAAA -B IIIII > o/sample_B4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G2-singles-clipped_filtered.fq -b TAGCGGA -B IIIIIII > o/sample_G2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F10-2-clipped_filtered.fq -b CGCTGAT -B IIIIIII > o/sample_F10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H7-2-clipped_filtered.fq -b CGTGTGGT -B IIIIIIII > o/sample_H7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A2-2-clipped_filtered.fq -b TGCA -B IIII > o/sample_A2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C5-singles-clipped_filtered.fq -b GGAAG -B IIIII > o/sample_C5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A6-singles-clipped_filtered.fq -b GCGT -B IIII > o/sample_A6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H9-2-clipped_filtered.fq -b GGATTGGT -B IIIIIIII > o/sample_H9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D10-singles-clipped_filtered.fq -b ATCGTA -B IIIIII > o/sample_D10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D7-1-clipped_filtered.fq -b AGTGGA -B IIIIII > o/sample_D7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C6-2-clipped_filtered.fq -b GTCAA -B IIIII > o/sample_C6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H8-singles-clipped_filtered.fq -b GCTGTGGA -B IIIIIIII > o/sample_H8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C11-2-clipped_filtered.fq -b CCAGCT -B IIIIII > o/sample_C11-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C1-2-clipped_filtered.fq -b ATTGA -B IIIII > o/sample_C1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A7-2-clipped_filtered.fq -b CGAT -B IIII > o/sample_A7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D1-singles-clipped_filtered.fq -b TAGGAA -B IIIIII > o/sample_D1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E12-1-clipped_filtered.fq -b GAATTCA -B IIIIIII > o/sample_E12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C5-2-clipped_filtered.fq -b GGAAG -B IIIII > o/sample_C5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B3-1-clipped_filtered.fq -b CTAGG -B IIIII > o/sample_B3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G10-2-clipped_filtered.fq -b TGGTACGT -B IIIIIIII > o/sample_G10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D5-1-clipped_filtered.fq -b GAGATA -B IIIIII > o/sample_D5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H10-2-clipped_filtered.fq -b GTGAGGGT -B IIIIIIII > o/sample_H10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H12-singles-clipped_filtered.fq -b TTCCTGGA -B IIIIIIII > o/sample_H12-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B2-2-clipped_filtered.fq -b TCACG -B IIIII > o/sample_B2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F8-singles-clipped_filtered.fq -b ATTGGAT -B IIIIIII > o/sample_F8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C2-singles-clipped_filtered.fq -b CATCT -B IIIII > o/sample_C2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E6-1-clipped_filtered.fq -b TAACGA -B IIIIII > o/sample_E6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F10-1-clipped_filtered.fq -b CGCTGAT -B IIIIIII > o/sample_F10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D11-singles-clipped_filtered.fq -b CATCGT -B IIIIII > o/sample_D11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C6-1-clipped_filtered.fq -b GTCAA -B IIIII > o/sample_C6-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F6-2-clipped_filtered.fq -b ACGTGTT -B IIIIIII > o/sample_F6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C9-2-clipped_filtered.fq -b TCGTT -B IIIII > o/sample_C9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C6-singles-clipped_filtered.fq -b GTCAA -B IIIII > o/sample_C6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C4-2-clipped_filtered.fq -b GAGGA -B IIIII > o/sample_C4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D10-2-clipped_filtered.fq -b ATCGTA -B IIIIII > o/sample_D10-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C2-1-clipped_filtered.fq -b CATCT -B IIIII > o/sample_C2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H2-2-clipped_filtered.fq -b AACCGAGA -B IIIIIIII > o/sample_H2-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A10-singles-clipped_filtered.fq -b GATG -B IIII > o/sample_A10-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B1-1-clipped_filtered.fq -b CGCTT -B IIIII > o/sample_B1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G8-2-clipped_filtered.fq -b TAGGCCAT -B IIIIIIII > o/sample_G8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B7-2-clipped_filtered.fq -b GTATT -B IIIII > o/sample_B7-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E9-1-clipped_filtered.fq -b CTTGCTT -B IIIIIII > o/sample_E9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C10-1-clipped_filtered.fq -b GGTTGT -B IIIIII > o/sample_C10-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C3-1-clipped_filtered.fq -b CCTAG -B IIIII > o/sample_C3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H12-1-clipped_filtered.fq -b TTCCTGGA -B IIIIIIII > o/sample_H12-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H11-singles-clipped_filtered.fq -b TATCGGGA -B IIIIIIII > o/sample_H11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H3-singles-clipped_filtered.fq -b ACAGGGAA -B IIIIIIII > o/sample_H3-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F4-2-clipped_filtered.fq -b AACGCCT -B IIIIIII > o/sample_F4-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E8-2-clipped_filtered.fq -b TATTTTT -B IIIIIII > o/sample_E8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B9-2-clipped_filtered.fq -b ACCGT -B IIIII > o/sample_B9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H2-singles-clipped_filtered.fq -b AACCGAGA -B IIIIIIII > o/sample_H2-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G11-singles-clipped_filtered.fq -b TCTCAGTG -B IIIIIIII > o/sample_G11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E9-2-clipped_filtered.fq -b CTTGCTT -B IIIIIII > o/sample_E9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_H9-singles-clipped_filtered.fq -b GGATTGGT -B IIIIIIII > o/sample_H9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F9-1-clipped_filtered.fq -b CATAAGT -B IIIIIII > o/sample_F9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D9-2-clipped_filtered.fq -b ATATGT -B IIIIII > o/sample_D9-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E5-1-clipped_filtered.fq -b GTTGAA -B IIIIII > o/sample_E5-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D6-singles-clipped_filtered.fq -b ATGCCT -B IIIIII > o/sample_D6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D8-1-clipped_filtered.fq -b ACCTAA -B IIIIII > o/sample_D8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B8-singles-clipped_filtered.fq -b CTGTA -B IIIII > o/sample_B8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A3-2-clipped_filtered.fq -b ACTA -B IIII > o/sample_A3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B8-2-clipped_filtered.fq -b CTGTA -B IIIII > o/sample_B8-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B7-1-clipped_filtered.fq -b GTATT -B IIIII > o/sample_B7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A9-singles-clipped_filtered.fq -b AGGG -B IIII > o/sample_A9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A1-singles-clipped_filtered.fq -b CTCG -B IIII > o/sample_A1-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B1-2-clipped_filtered.fq -b CGCTT -B IIIII > o/sample_B1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D3-1-clipped_filtered.fq -b CCACAA -B IIIIII > o/sample_D3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C9-1-clipped_filtered.fq -b TCGTT -B IIIII > o/sample_C9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E1-2-clipped_filtered.fq -b CTATTA -B IIIIII > o/sample_E1-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G6-2-clipped_filtered.fq -b ACGACTAG -B IIIIIIII > o/sample_G6-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F3-1-clipped_filtered.fq -b GTCGATT -B IIIIIII > o/sample_F3-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G7-1-clipped_filtered.fq -b TAGCATGG -B IIIIIIII > o/sample_G7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A7-singles-clipped_filtered.fq -b CGAT -B IIII > o/sample_A7-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B11-1-clipped_filtered.fq -b GGTGT -B IIIII > o/sample_B11-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B5-singles-clipped_filtered.fq -b TTCTG -B IIIII > o/sample_B5-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G3-2-clipped_filtered.fq -b TCGAAGA -B IIIIIII > o/sample_G3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D3-2-clipped_filtered.fq -b CCACAA -B IIIIII > o/sample_D3-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_F5-2-clipped_filtered.fq -b AATATGG -B IIIIIII > o/sample_F5-2-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G9-1-clipped_filtered.fq -b TGCAAGGA -B IIIIIIII > o/sample_G9-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D9-singles-clipped_filtered.fq -b ATATGT -B IIIIII > o/sample_D9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C7-1-clipped_filtered.fq -b TAATA -B IIIII > o/sample_C7-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A8-singles-clipped_filtered.fq -b GTAA -B IIII > o/sample_A8-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A4-singles-clipped_filtered.fq -b CAGA -B IIII > o/sample_A4-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C9-singles-clipped_filtered.fq -b TCGTT -B IIIII > o/sample_C9-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_B6-singles-clipped_filtered.fq -b AGCCG -B IIIII > o/sample_B6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_A11-singles-clipped_filtered.fq -b TCAG -B IIII > o/sample_A11-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_D2-1-clipped_filtered.fq -b GCTCTA -B IIIIII > o/sample_D2-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_C8-1-clipped_filtered.fq -b TACAT -B IIIII > o/sample_C8-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_E6-singles-clipped_filtered.fq -b TAACGA -B IIIIII > o/sample_E6-singles-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G1-1-clipped_filtered.fq -b GCGGAAT -B IIIIIII > o/sample_G1-1-clipped_filtered.fq
/home/kevin/bin/seqtk seq p1/sample_G1-singles-clipped_filtered.fq -b GCGGAAT -B IIIIIII > o/sample_G1-singles-clipped_filtered.fq
